apiVersion: v1
kind: Pod
metadata:
  name: testing-service
spec:
  containers:
    - name: test-ser
      image: docker.io/jagadesh1982/testing-service
      ports:
      - containerPort: 9876
  initContainers:
    - name:         precont
      image:        docker.io/jagadesh1982/bashalpine:latest
      imagePullPolicy: IfNotPresent
      command:
          - "bash"
          - "-c"
          - "for ((i=1;i<=10;i++)) ; do echo '$(date +%F-%T) Log output' >> Output.txt ; sleep 3;  done"


# Wait for some time before starting the app Container with a command like sleep 60.
# Clone a git repository into a volume.
# Place values into a configuration file and run a template tool to dynamically generate a configuration file for the main app Container. 
# For example, place the POD_IP value in a configuration and generate the main app configuration file using Jinja.
