apiVersion: v1
kind: Pod
metadata:
  name: pod-init-container
  labels:
    env: dev
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876 
  initContainers:
    - name: sleepy
      image: alpine
      imagePullPolicy: IfNotPresent
      command: ['sleep', '20']
    - name: counter
      image: alpine
      command:
        - "bin/sh"
        - "-c"
        - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done" 
        
        
        
   
