apiVersion: v1
kind: Pod
metadata:
  name: single-pod-init-container
  labels:
    env: dev
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876 
  initContainers:
    - name: counter
      image: centos:7
      imagePullPolicy: IfNotPresent
      command:
        - "bin/bash"
        - "-c"
        - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"   
