apiVersion: v1
kind: Pod
metadata:
  name: logme
spec:
  containers:
  - name: logging
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "while true; do echo $(date) | tee /dev/stderr; sleep 1; done"

#To view the five most recent log lines of the logging container in the logme pod,
#[root@k8s-master k8s-workloads]# kubectl logs --tail=5 logme -c logging
#To stream the log of the logging container in the logme pod (like tail -f), do:
#[root@k8s-master k8s-workloads]# kubectl logs -f --since=10s logme -c logging
