apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    env: dev
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876 
  - name: shell
    image: centos:7
    command:
      - "/usr/bin/bash"
      - "-c"
      - "sleep 10000"
