apiVersion: v1
kind: Pod
metadata:
  name: single-pod3
  labels:
    env: prod
    tier: backend
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876  
