apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-1
  labels:
    env: dev
    type: aws-ebs
spec:
 capacity:
   storage: 5Gi
 accessModes:
   - ReadWriteOnce
 awsElasticBlockStore:
   volumeID: vol-01997322a2a934cf0
   fsType: ext4
