apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol-1
  labels:
    env: dev
    type: aws-ebs
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
    storage: 3Gi
 selector:
   matchLabels:
     type: "aws-ebs"
