apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
   env: dev
spec:
  containers:
  - image: nginx
    name: testing-service
    ports:
     - containerPort: 80
    volumeMounts:
     - name: apikeyvol
       mountPath: "/tmp/apikey"
       readOnly: true
  volumes:
     - name: apikeyvol
       configMap:
        - key: config
          path: example-configmap



#echo 'admin' | base64
#echo 'password' | base64 
