apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  labels:
    env: dev
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876 
    volumeMounts:
       - mountPath: /data-mount
         name: data
  volumes:
    - name: data
      gitRepo:
        repository: "https://github.com/jagadesh1982/SampleTest.git"
