apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  labels:
    env: dev
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876 
    volumeMounts:
     - name: test-nfs
       mountPath: /demo 
  volumes:
   - name: test-nfs
     awsElasticBlockStore:
       volumeID: vol-01997322a2a934cf0
       fsType: ext4

