apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
   env: dev
spec:
  containers:
  - image: nginx
    name: testing-service
    ports:
     - containerPort: 80
    volumeMounts:
     - name: apikeyvol
       mountPath: "/tmp/apikey"
       readOnly: true
  volumes:
     - name: apikeyvol
       secret:
         secretName: apikey   
