apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  labels:
    env: dev
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876 
    lifecycle:
       postStart:
          exec:
            command: ["/bin/sh", "-c", "touch /tmp/hello"]
       preStop:
          exec:
            command: ["/bin/sh", "-c", "echo Hello from the preSop handler > /tmp/hello"]

   
