apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-label
  labels:
    app: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sub-label
      env: dev
  template:
    metadata:
      labels:
        app: sub-label
        env: dev
    spec:
      containers:
       - name: test-ser
         image: docker.io/jagadesh1982/testing-service
         ports:
          - containerPort: 9876 
