apiVersion: v1
kind: Service
metadata:
   name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    version: "1.0"
  ports:
    - port: 8888
      targetPort: 80


# Once the first version of canary deployment is done. remove the version: "1.0" and save before running the second version of the canary deployment
