apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
  labels:
   env: dev
spec:
  containers:
  - image: nginx
    name: testing-service
    ports:
     - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-volume
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: nfs-pvc
