apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: ATTENDED_STUDENTS 
          valueFrom:
            configMapKeyRef:
              name: class-data    
              key: attended_students 
        - name: STUDENT_FILES
          valueFrom:
            configMapKeyRef:
              name: class-data
              key: student_files
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: class-data
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "student.properties"
          path: "student.properties"
        - key: "student-interface.properties"
          path: "student-interface.properties"
