apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  labels:
   env: dev
spec:
  containers:
  - image: nginx
    name: testing-service
    ports:
     - containerPort: 80
    volumeMounts:
     - name: configmap
       mountPath: "/tmp/apikey"
       readOnly: true
  volumes:
     - name: configmap
       configMap:
        name: example-configmap
        items: 
         - key: config
           path: example-map


#echo 'admin' | base64
#echo 'password' | base64 
