apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: nginx:1.7.9
    name: test
    volumeMounts:
    - mountPath: /test
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
    persistentVolumeClaim:
      claimName: hostpath


# hostPath-pv.yml
# hostPath-pvc.yml
