apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
    - default:
        cpu: 200m
        memory: 6Mi
      defaultRequest:
        cpu: 100m
        memory: 5Mi
      type: Container    
