apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-demo
spec:
  hard:
    pods: "2"



# kubectl run nginx --image=nginx --restart=Never --namespace=pod-demo
# kubectl run tomcat --image=tomcat:8.0 --namespace=pod-demo
# kubectl run -i --tty busybox --image=busybox --restart=Never --namespace=pod-demo
