apiVersion: v1
kind: Service
metadata:
  name: green-svc
spec:
  ports:
    - port: 8080
      targetPort: 9876
  selector:
    env: dev
    tier: backend
    version: "2.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-dm
  labels:
    app: testing-service
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      tier: backend
      version: "2.0"
  template:
    metadata:
      labels:
        env: dev
        tier: backend
        version: "2.0"
    spec:
      containers:
       - name: test-service
         image: docker.io/jagadesh1982/testing-service:latest
         ports:
          - containerPort: 9876 
         env:
          - name: VERSION
            value: "2.0"
          - name: FRUIT
            value: "grape"
