apiVersion: v1
kind: ReplicationController
metadata:
  name: testing-service
  labels:
    env: dev
    tier: backend
spec:
  replicas: 3
  selector:
     env: dev
     app: testing-service
     version: "1"
  template:
    metadata:
      labels:
        env: dev
        app: testing-service
        version: "1"
    spec:
      containers:
        - name: test-service
          image: "docker.io/jagadesh1982/testing-service"
          ports:
           - containerPort: 9876
