apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: docker.io/jagadesh1982/testing-service:3
    ports:
     - containerPort: 9876
    env:
      - name: VERSION
        value: "1.0"
      - name: FRUIT
        value: "mango"
      - name: SLEEP
        value: "50"   
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/test.txt
      initialDelaySeconds: 5
      periodSeconds: 5
