apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: docker.io/jagadesh1982/testing-service:3
    ports:
     - containerPort: 9876
    env:
      - name: VERSION
        value: "1.0"
      - name: FRUIT
        value: "mango"
      - name: SLEEP
        value: "15"   
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      httpGet:
        path: /info
        port: 9876

# Http Fields
# host: Host name to connect to, defaults to the pod IP. You probably want to set "Host" in httpHeaders instead.
# scheme: Scheme to use for connecting to the host (HTTP or HTTPS). Defaults to HTTP.
# path: Path to access on the HTTP server. Defaults to /.
# httpHeaders: Custom headers to set in the request. HTTP allows repeated headers.
# port: Name or number of the port to access on the container. Number must be in the range 1 to 65535.
