apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: dev
    version: "2"
    tier: frontend
spec:
  containers:
    - image: centos:7
      name: cont1
      command:
       - "/bin/bash"
       - "-c"
       - "touch /tmp/test; sleep 30; rm -rf /tmp/test; sleep 600"
      livenessProbe:
        exec:
         command:
           - cat
           - /tmp/test
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 2
        successThreshold: 1
        timeoutSeconds: 2


# Many applications running for long periods of time eventually transition to broken states, and cannot recover except by being restarted. 
# Kubernetes provides liveness probes to detect and remedy such situations. # The periodSeconds field specifies that the kubelet should perform 
# a liveness probe every 5 seconds. The initialDelaySeconds field tells the kubelet that it should wait 5 seconds before performing the first probe. 

# To perform a probe, the kubelet executes the command cat /tmp/test in the target container. If the command succeeds, it returns 0, and the kubelet 
# considers the container to be alive and healthy. If the command returns a non-zero value, the kubelet kills the container and restarts it

