apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: docker.io/jagadesh1982/testing-service:3
    ports:
     - containerPort: 9876
    env:
      - name: VERSION
        value: "1.0"
      - name: FRUIT
        value: "mango"
      - name: SLEEP
        value: "15"   
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      httpGet:
        path: /info
        port: 9876
