apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  labels:
    env: dev
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876 
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      exec:
        command:
         - cat
         - /testing_service.py
