apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  labels:
    env: dev
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876
    env:
      - name: VERSION
        value: "1.0"
      - name: FRUIT
        value: "mango"
      - name: SLEEP
        value: "50"    
    readinessProbe:
      tcpSocket:
        port: 9876
      initialDelaySeconds: 5
      periodSeconds: 10 
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
        path: /info
        port: 9876
