apiVersion: batch/v1
kind: Job
metadata:
  name: single-job
spec:
  backoffLimit: 6 # number of retries before throwing error
  activeDeadlineSeconds: 10 # time to allow job to run
  template:
    metadata:
      labels:
        env: dev
    spec:
      restartPolicy: OnFailure
      containers:
        - name: testing-job
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never



# Container restart policy
#The spec of a Pod has a restartPolicy field with possible values Always, OnFailure, and Never. The default value is Always.
# The restartPolicy applies to all containers in the Pod. restartPolicy only refers to restarts of the containers by the kubelet on the same node. 
# After containers in a Pod exit, the kubelet restarts them with an exponential back-off delay (10s, 20s, 40s, …), that is capped at five minutes. 
# Once a container has executed for 10 minutes without any problems, the kubelet resets the restart backoff timer for that container.


