apiVersion: batch/v1
kind: Job
metadata:
  name: completion-job
spec:
  completions: 3 # number of times to run 
  backoffLimit: 6 # number of retries before throwing error
  activeDeadlineSeconds: 10 # time to allow job to run
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: testing-job
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never


# Job completion count :A Job is completed when a specific number of Pods terminate successfully. By default, a non-parallel Job with a single Pod completes 
# as soon as the Pod terminates successfully. If you have a parallel Job, you can set a completion count using the optional completions field. 
# This field specifies how many Pods should terminate successfully before the Job is complete. The completions field accepts a non-zero, positive value.Omitting 
# completions or specifying a zero value causes the success of any Pod to signal the success of all Pods.
