apiVersion: v1
kind: Pod
metadata:
  name: besteffort
spec:
  containers:
    - name: container
      image: busybox
      command: [ /bin/sleep, 1d ]
      resources:
        limits:
          cpu: 0
          memory: 0
        requests:
          cpu: 0
          memory: 0
