apiVersion: v1
kind: Pod
metadata:
  name: burstable
spec:
  containers:
    - name: container
      image: busybox
      command: [ /bin/sleep, 1d ]
      resources:
        limits:
          cpu: 100m
          memory: 10Mi
        requests:
          cpu: 100m
          memory: 0
