apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-deployment
  labels:
    env: dev
    app: testing-service
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testing-service
  template:
    metadata:
      labels:
        app: testing-service
        tier: backend
        env: dev
        type: deploy
    spec:
      containers:
       - name: testing-service
         image: docker.io/jagadesh1982/testing-service
         ports:
          - containerPort: 9876
      tolerations: 
       - key: machine 
         operator: Equal 
         value: test 
         effect: NoSchedule    
