apiVersion: v1
kind: Service
metadata:
  name: testing-service-svc
  labels:
    app: testing-service
spec:
  ports:
  - port: 9876
    protocol: TCP
    targetPort: 80
  selector:
    app: testing-service
    tier: backend
    env: dev
    type: deploy
