apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: docker.io/jagadesh1982/testing-service
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  restartPolicy: Never



# Most environment variables in the Kubernetes API use the value field to carry simple values. However, the alternate valueFrom field 
# allows you to specify a fieldRef to select fields from the pod’s definition. The fieldRef field is a structure that has an apiVersion
# field and a fieldPath field. The fieldPath field is an expression designating a field of the pod.
# The apiVersion field is the version of  the API schema that the fieldPath is written in terms of.
#If the apiVersion field is not specified it is defaulted to the API version of the enclosing object.

# The fieldRef is evaluated and the resulting value is used as the value for the environment variable.
# This allows users to publish their pod’s name in any environment variable they want.
