apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  labels:
    env: dev
    version: "1"
    tier: frontend
spec:
  containers:
  - name: testing-service
    image: docker.io/jagadesh1982/testing-service:latest
    ports:
     - containerPort: 9876
