apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4K
  password: cGFzc3dvcmQK


#echo 'admin' | base64
#echo 'password' | base64
# echo 'YWRtaW4K' | base64 --decode
